routes/web.php
<?php
    
    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */
    Route::group(['middleware' => 'prevent-back-history'], function () {
        Auth::routes();
        Route::get('/home', 'HomeController@index');
    });
    
    Route::get('/', 'HomeController@index')->name('home');
    
    Auth::routes();
    
    Route::get('/home', 'HomeController@index')->name('home');


//use Illuminate\Support\Facades\Artisan;
//use Illuminate\Support\Facades\Route;

//Route::get('/', function () {
//    return view('auth.login');
//});
//
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');
    
    Route::group(['middleware' => ['role_or_permission:super-admin']], function () {
        
        Route::post('updateRolesPermissions', 'PermissionController@updateRolesPermissions');
        Route::resource('users', 'UserController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('roles', 'RoleController');
        
        
    });
    Route::resource('/companies', 'CompanyController');
    
    
    Route::put('/paysheet/paysheetCancel/{id}', 'paysheetController@paysheetCancel')->name('paysheet.paysheetCancel');
    Route::put('/paysheet/paysheetApprove/{id}', 'paysheetController@paysheetApprove')->name('paysheet.paysheetApprove');
    
    Route::post('/paysheetCancelAll', 'paysheetController@paysheetCancelAll')->name('paysheet.paysheetCancelAll');
    Route::put('/paysheetCancelAll', 'paysheetController@paysheetCancelAll')->name('paysheet.paysheetCancelAll');
    
    Route::post('/paysheetApproveAll', 'paysheetController@paysheetApproveAll')->name('paysheet.paysheetApproveAll');
    Route::put('/paysheetApproveAll', 'paysheetController@paysheetApproveAll')->name('paysheet.paysheetApproveAll');
    
    /*------------------------------------------------------------------*/
    /*                      System Routes
    /*------------------------------------------------------------------*/
    Route::post('/attendances/generateAttendanceReport', 'AttendanceController@generateAttendanceReport')->name('attendance.generateAttendanceReport');
    Route::get('/attendances/getAttendanceReport', 'AttendanceController@getAttendanceReport')->name('attendance.getAttendanceReport');
    Route::get('/attendances/getSampleAttendance', 'AttendanceController@getSampleAttendance')->name('getSampleAttendance');
    
    Route::post('/employees/image/{id}', 'employeeController@profile')->name('employees.profile');
    Route::get('/employees/getbranches', 'employeeController@getbranches')->name('employees.getbranches');
    Route::get('/employee-list/{id}', 'employeeController@emp_list')->name('employees.emp_list');
    Route::get('/employees/filter', 'employeeController@filter')->name('employees.filter');
    Route::get('/employees/export', 'employeeController@export')->name('employees.export');
    Route::get('/employees/profile', 'employeeController@emp_profile')->name('employees.emp_profile');
    Route::resource('/employees', 'employeeController');
    Route::post('/employees/saveEmployee', 'employeeController@store')->name('saveEmployee');
    Route::post('/employees/updateEmployee', 'employeeController@update')->name('updateEmployee');
    Route::post('selected/company', 'HomeController@setCompany')->name('setCompany');
    
    Route::post('/leaves_balance/getBalance', 'LeaveBalanceController@getBalance')->name('leaves_balance.getBalance');
    Route::resource('/leaves', 'LeaveController');
    Route::resource('/leaves_balance', 'LeaveBalanceController');
    
    Route::post('/payroll-approval', 'SalaryController@approve')->name('payroll.approve');
    
    Route::get('/payroll-approval', 'SalaryController@payrole_approval')->name('payroll.approval');
    
    Route::resource('/salary', 'SalaryController');
    
    Route::resource('/events', 'EventsController');
    
    Route::post('/paysheet/print', 'paysheetController@print_sheet')->name('paysheet.print');
    
    Route::post('/paysheet/payrole_with_file', 'paysheetController@payrole_with_file')->name('paysheet.payrole_with_file');
    
    Route::resource('/paysheet', 'paysheetController');
    
    Route::resource('/payslip', 'payslipController');
    
    Route::get('/employee-payslip', 'payslipController@employee_payslip')->name('payslip.employee_payslip');
    
    Route::resource('/payadvice', 'payadviceController');
    
    Route::resource('/bankfile', 'bankfileController');
    
    Route::resource('/epfcform', 'epfcformController');
    
    Route::resource('/wht', 'whtController');
    
    Route::get('importExport', 'AttendanceController@importExport');
    
    Route::post('/paysheet/payRole', 'AttendanceController@payRole')->name('attendance.payRole');
    
    Route::get('downloadExcel/{type}', 'AttendanceController@downloadExcel');
    
    Route::post('importExcel', 'AttendanceController@importExcel');
    
    Route::resource('/attendances', 'AttendanceController');
    
    Route::resource('/employee_loans', 'LoanController');
    
    Route::get('/department', 'SettingController@department')->name('settings.department');
    
    Route::post('/department', 'SettingController@store_department')->name('settings.store_department');
    
    Route::get('/department_edit', 'SettingController@edit_department')->name('settings.edit_department');
    
    Route::put('/department_update', 'SettingController@update_department')->name('settings.update_department');
    
    Route::delete('/department_delete/{id}', 'SettingController@delete_department')->name('settings.delete_department');
    
    Route::get('/theme', 'SettingController@theme')->name('settings.theme');
    
    Route::put('/companies/logo_update/{id}', 'CompanyController@logo_update')->name('companies.logo_update');
    
    Route::put('/companies/bank_update/{id}', 'CompanyController@bank_update')->name('companies.bank_update');
    
    Route::put('/companies/tax_details_update/{id}', 'CompanyController@tax_details_update')->name('companies.tax_details_update');
    
    Route::put('/companies/profile_conatcts_update/{id}', 'CompanyController@profile_conatcts_update')->name('companies.profile_conatcts_update');
    
    Route::put('/companies/leave_details_update/{id}', 'CompanyController@leave_details_update')->name('companies.leave_details_update');
    Route::post('/companies/assignUserToCompany', 'CompanyController@assignUserToCompany');
    
    Route::get('/clear-cache', function () {
        $exitCode = Artisan::call('config:clear');
        $exitCode = Artisan::call('cache:clear');
        $exitCode = Artisan::call('config:cache');
        $exitCode = Artisan::call('view:clear');
        $exitCode = Artisan::call('route:clear');
        return 'DONE';
    });
    
    
    Route::get('/storage', function () {
        
        symlink('/home/clientcorporates/ERP/storage/app/public', '/home/clientcorporates/public_html/storage');
        
        echo "Storage Linked";
    });
    
    
    Route::get('/mail', 'MailController@index')->name('Mail.index');
    
    Route::post('/send', 'MailController@send_mail')->name('Mail.send');
    
    Route::post('/bankfile/getBnkFile', 'bankfileController@downloadBankFileText')->name('GetBankFile');
    Route::post('/bankfile/getEpfFile', 'epfcformController@downloadEpfFileText')->name('GetEpfFile');
    Route::post('/bankfile/getEtfFile', 'epfcformController@downloadEtfFileText')->name('GetEtfFile');
    Route::post('/attendances/getAttendance', 'AttendanceController@filterAttendance')->name('GetAttendance');
    
    Route::get('/employees/getReportingManager', 'employeeController@getReportingManager')->name('employees.getReportingManager');
    Route::post('/shifts/destroyShift','CompanyController@destroyShift')->name('destroyShift');
    
    Route::get('/temp/{id}', 'SettingController@temp')->name('settings.temp');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{

    public function salary(){
        return $this->hasOne('App\Salary','employee_id','user_id');
    }

    public function company(){
        return $this->belongsTo('App\Company','regno','company_id');
    }
    
    public function attend(){
        return $this->hasMany('App\Employee_Attendance','user_id','user_id')->where('companyId', session('company_id'));
    }
    
    public function allowance(){
        return $this->hasOne('App\Allowance','company_id','company_id');
    }
    
    public function myShift(){
        return $this->hasOne('App\Shift','id','shift');
    }
    
    public function departments(){
        return $this->hasOne('App\Department','id','department');
    }
    
    public function leaves(){
        return $this->hasMany('App\Leave', 'user_id', 'user_id');
    }
    
    public function leaveBalance(){
        return $this->hasMany('App\Leave_balance', 'user_id', 'user_id');
    }
}

resources/views/employee/company_employee.blade.php
@extends('layouts.app')

@section('title')
    <title>Talent | Employee</title>
@endsection

@section('page_header')
    <h5 class="m-0 text-dark">Employee Management</h5>
@endsection

@section('pagenation')
    <li class="breadcrumb-item"><a href="{{'/home'}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Employee</li>
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <div class="pull-right">
                </div>
            </h3>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped" id="example1">
                <thead>
                <tr>
                    <th class="search">Emp ID</th>
                    <th class="search">Name</th>
                    <th class="search">E-mail</th>
                    <th class="search">NIC</th>
                    <th class="search">Contact Number</th>
                    <th class="search">Gender</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody id="table">
                @foreach($employees as $employee)

                    <tr>
                        <td>{{ $employee->user_id }}</td>
                        <td>{{ $employee->sname }} {{ $employee->fname }} {{ $employee->lname }}</td>
                        <td>{{ $employee->personal_email }}</td>
                        <td>{{ $employee->nic }}</td>
                        <td>{{ $employee->per_mobileno }}</td>
                        <td>{{ $employee->gender }}</td>
                        <td>

                            @can('view employees')
                                <a class="btn btn-circle btn-info btn-sm" href="{{ route('employees.show', $employee->id) }}" data-toggle="tooltip" title="View"><i class="fa fa-file-text-o" aria-hidden="true"></i></a>
                            @endcan

                            @can('edit employees')
                                <a class="btn btn-circle btn-success btn-sm" href="{{ route('employees.edit', $employee->id) }}" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            @endcan

                            @can('delete employees')
                                <button class="btn btn-danger btn-sm" data-employeeid="{{$employee->id}}" data-toggle="modal" data-target="#delete"><i class="fa fa-trash" aria-hidden="true" data-toggle="tooltip" title="Delete"></i></button>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>

            </table>
        </div>

        <div class="row">

            <div class="col-3" style="margin-bottom: 15px; margin-left: 25px;">
                <a class="btn btn-success btn-sm" href="{{url()->previous()}}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</a>
            </div>
        </div>
    </div>


    <!-- delete modal -->
    <div id="delete" class="modal fade" role=".modal-dialog-centered">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="icon-box">
                        <i class="material-icons">&#xE5CD;</i>
                    </div>
                </div>
                <h1>Are you Sure ?</h1>

                <form action="{{ route('employees.destroy', '0') }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE')}}
                    <div class="modal-body">
                        <input type="hidden" name="employee_id" value="" id="employee_id">
                        <p>Do you really want to delete these records? This process cannot be undone.</p>
                    </div>
                    <div class="modal-footer"></div>
                    <div class="row justify-content-md-center">
                        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>&nbsp;&nbsp;
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('custom-jquery')
    <script>
        $('#delete').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var id = button.data('employeeid');
            console.log(id);
            var modal = $(this)
            modal.find('#employee_id').val(id);
        });


        $('#to').change(function(event) {
            console.log("inside");
            var fromEmp =  $("#from :selected").val();

            if(from!='Select From'){
                var toEmp = $('#to').val();
                console.log(to);

                console.log(from);

                {{--$.ajax({--}}
                {{--    url:"{{ route('employees.filter') }}",--}}
                {{--    method: "get",--}}
                {{--    data: {from:fromEmp,to:toEmp},--}}
                {{--    datatype: "json",--}}
                {{--    success:function (data) {--}}

                {{--        $('#table').html(data.html);--}}

                {{--    }--}}
                {{--});--}}
            }

        });


    </script>
@endsection

resources/views/employee/employee_skill.blade.php
@extends('layouts.app')

@section('title')
    <title>Talent | Skills & Talents</title>
@endsection

@section('page_header')
    <h5 class="m-0 text-dark">Employee Management</h5>
@endsection

@section('pagenation')
    <li class="breadcrumb-item"><a href="{{ route('employees.index') }}">Employee</a></li>
    <li class="breadcrumb-item active">Skills and talents</li>
@endsection

@section('content')
<div class="row justify-content-center">
<div class="col-md-9">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><b>Skills and talents</b></h3>
        </div><!--card-header-->

        <div class="card-body">
        <form action="{{ route('employee_skills.store') }}" method="POST">
            {{ csrf_field() }}
            <div class="form-group">
                
                <div class="form-row">
                    <div class="col">
                        <label>Employee ID</label>
                        <select class="custom-select" name="emp_id">
                            <option selected>Select the Employee</option>
                            @foreach($employees as $employee)
                                @if($employee->company_id == auth()->user()->company_id )
                                    <option value="{{ $employee->user_id }}">{{ $employee->sname }}({{ $employee->user_id }})</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <label>Skill type</label>
                        <select class="custom-select" name="skill_type">
                            <option selected>Select the skill type</option>
                            <option value="Academic" >Academic</option>
                            <option value="Non-Academic">Non-Academic</option>
                        </select>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <label>Skill or talent</label>
                        <input type="text" class="form-control" name="skill" placeholder="Skill or talent">
                    </div>
               </div>
               <div class="form-row">
                    <div class="col">
                        <label>Description</label>
                        <textarea class="form-control" rows="3" name="desp" placeholder="Description" ></textarea>
                
                    </div>
               </div>


                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Add</button>
                </div><!--modal-footer-->

            </form>
            </div>


        </div><!--card-body -->
    </div>
</div>
</div>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Talent | Employee</title>
@endsection

@section('page_header')
    <h5 class="m-0 text-dark">Employee Management</h5>
@endsection

@section('pagenation')
    <li class="breadcrumb-item"><a href="{{'/home'}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Employee</li>
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <div class="pull-left">

                </div>
                <div class="pull-right">
                    {{--                    @can('create employees')--}}
                    <a href="{{ route('employees.create') }}" class="btn btn-success btn-sm" data-toggle="tooltip"
                       data-placement="top" title="New"><i class="fa fa-plus"></i></a>
                    {{--                    @endcan--}}
                </div>
            </h3>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped" id="example1">
                <thead>
                <tr>
                    <th class="search">Emp ID</th>
                    <th class="search">Name</th>
                    <th class="search">E-mail</th>
                    {{--                    <th class="search">NIC</th>--}}
                    <th class="search">Contact Number</th>
                    {{--                    <th class="search">Gender</th>--}}
                    <th class="search">Date Of Join</th>
                    <th class="search">Date Of Seperation</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody id="table">
                @if(!is_null($employees))
                    @foreach($employees as $employee)
                        <tr>
                            @if(!is_null($employee->date_of_resign))
                                <td class="resign">{{ $employee->user_id }}</td>
                                <td class="resign">{{ $employee->name_with_initials }}</td>
                                <td class="resign">{{ $employee->personal_email }}</td>
                                <td class="resign">{{ $employee->per_mobileno }}</td>
                                <td class="resign">{{ $employee->date_of_join }}</td>
                                <td class="resign">{{ $employee->date_of_resign }}</td>
                                <td class="resign">

                                    @can('view employees')
                                        <a class="btn btn-circle btn-info btn-sm"
                                           href="{{ route('employees.show', $employee->id) }}" data-toggle="tooltip"
                                           title="View"><i class="fa fa-file-text-o" aria-hidden="true"></i></a>
                                    @endcan

                                    @can('edit employees')
                                        <a class="btn btn-circle btn-success btn-sm"
                                           href="{{ route('employees.edit', $employee->id) }}" data-toggle="tooltip"
                                           title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                    @endcan

                                    @can('delete employees')
                                        <button class="btn btn-danger btn-sm" data-employeeid="{{$employee->id}}"
                                                data-toggle="modal" data-target="#delete"><i class="fa fa-trash"
                                                                                             aria-hidden="true"
                                                                                             data-toggle="tooltip"
                                                                                             title="Delete"></i>
                                        </button>
                                    @endcan
                                    @if($employee->date_of_resign == null)
                                        <button class="btn btn-warning btn-sm" data-employeeid="{{$employee->id}}"
                                                data-toggle="modal" data-target="#separate"><i class="fa fa-sign-out"
                                                                                               aria-hidden="true"
                                                                                               data-toggle="tooltip"
                                                                                               title="Separate"></i>
                                        </button>
                                    @endif
                                </td>
                            @else
                                <td>{{ $employee->user_id }}</td>
                                <td>{{ $employee->name_with_initials }}</td>
                                <td>{{ $employee->personal_email }}</td>
                                <td>{{ $employee->per_mobileno }}</td>
                                <td>{{ $employee->date_of_join }}</td>
                                <td>{{ $employee->date_of_resign }}</td>
                                <td>

                                    @can('view employees')
                                        <a class="btn btn-circle btn-info btn-sm"
                                           href="{{ route('employees.show', $employee->id) }}" data-toggle="tooltip"
                                           title="View"><i class="fa fa-file-text-o" aria-hidden="true"></i></a>
                                    @endcan

                                    @can('edit employees')
                                        <a class="btn btn-circle btn-success btn-sm"
                                           href="{{ route('employees.edit', $employee->id) }}" data-toggle="tooltip"
                                           title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                    @endcan

                                    @can('delete employees')
                                        <button class="btn btn-danger btn-sm" data-employeeid="{{$employee->id}}"
                                                data-toggle="modal" data-target="#delete"><i class="fa fa-trash"
                                                                                             aria-hidden="true"
                                                                                             data-toggle="tooltip"
                                                                                             title="Delete"></i>
                                        </button>
                                    @endcan
                                    @if($employee->date_of_resign == null)
                                        <button class="btn btn-warning btn-sm" data-employeeid="{{$employee->id}}"
                                                data-toggle="modal" data-target="#separate"><i class="fa fa-sign-out"
                                                                                               aria-hidden="true"
                                                                                               data-toggle="tooltip"
                                                                                               title="Separate"></i>
                                        </button>
                                    @endif
                                </td>
                            @endif
                        </tr>
                    @endforeach
                @endif
                </tbody>

            </table>
        </div>

        <div class="row">

            <div class="col-3" style="margin-bottom: 15px; margin-left: 25px;">
                <a class="btn btn-success btn-sm" href="{{url()->previous()}}"><i class="fa fa-arrow-left"
                                                                                  aria-hidden="true"></i> Back</a>
            </div>
        </div>
    </div>


    <div id="separate" class="modal fade" role=".modal-dialog-centered">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    @php $company = session('company'); @endphp
                    @if(isset($company))
                        <h4>Separation with {{ App\company::find(session('company'))->name }}</h4>
                    @endif
                </div>
                <form action="{{ route('employees.update', '0') }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT')}}
                    <div class="modal-body">
                        <div class="form-group">
                            <lable>Separation Date</lable>
                            <input type="date" id="separation_date" name="separation_date" class="form-control">
                        </div>
                        <div class="form-group">
                            <lable>Remarks</lable>
                            <textarea name="remarks_for_separation" id="remarks_for_separation" cols="20"
                                      class="form-control" rows="5"></textarea>
                        </div>
                        <input type="hidden" name="employee_id" value="" id="employee_id">
                    </div>
                    <div class="modal-footer"></div>
                    <div class="row justify-content-md-center">
                        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>&nbsp;&nbsp;
                        <button type="submit" class="btn btn-danger">Separate</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- delete modal -->
    <div id="delete" class="modal fade" role=".modal-dialog-centered">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="icon-box">
                        <i class="material-icons">&#xE5CD;</i>
                    </div>
                </div>
                <h1>Are you Sure ?</h1>

                <form action="{{ route('employees.destroy', '0') }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE')}}
                    <div class="modal-body">
                        <input type="hidden" name="employee_id" value="" id="employee_id">
                        <p>Do you really want to delete these records? This process cannot be undone.</p>
                    </div>
                    <div class="modal-footer"></div>
                    <div class="row justify-content-md-center">
                        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>&nbsp;&nbsp;
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('custom-jquery')
    <script>
        $('#separate').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var id = button.data('employeeid');
            console.log(id);
            var modal = $(this)
            modal.find('#employee_id').val(id);
        });

        $('#delete').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var id = button.data('employeeid');
            console.log(id);
            var modal = $(this)
            modal.find('#employee_id').val(id);
        });


        $('#to').change(function (event) {
            console.log("inside");
            var fromEmp = $("#from :selected").val();

            if (from != 'Select From') {
                var toEmp = $('#to').val();
                console.log(to);

                console.log(from);

                {{--$.ajax({--}}
                {{--    url:"{{ route('employees.filter') }}",--}}
                {{--    method: "get",--}}
                {{--    data: {from:fromEmp,to:toEmp},--}}
                {{--    datatype: "json",--}}
                {{--    success:function (data) {--}}

                {{--        $('#table').html(data.html);--}}

                {{--    }--}}
                {{--});--}}
            }

        });


    </script>
@endsection