routes/web.php
<?php
    
    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */
    Route::group(['middleware' => 'prevent-back-history'], function () {
        Auth::routes();
        Route::get('/home', 'HomeController@index');
    });
    
    Route::get('/', 'HomeController@index')->name('home');
    
    Auth::routes();
    
    Route::get('/home', 'HomeController@index')->name('home');


//use Illuminate\Support\Facades\Artisan;
//use Illuminate\Support\Facades\Route;

//Route::get('/', function () {
//    return view('auth.login');
//});
//
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');
    
    Route::group(['middleware' => ['role_or_permission:super-admin']], function () {
        
        Route::post('updateRolesPermissions', 'PermissionController@updateRolesPermissions');
        Route::resource('users', 'UserController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('roles', 'RoleController');
        
        
    });
    Route::resource('/companies', 'CompanyController');
    
    
    Route::put('/paysheet/paysheetCancel/{id}', 'paysheetController@paysheetCancel')->name('paysheet.paysheetCancel');
    Route::put('/paysheet/paysheetApprove/{id}', 'paysheetController@paysheetApprove')->name('paysheet.paysheetApprove');
    
    Route::post('/paysheetCancelAll', 'paysheetController@paysheetCancelAll')->name('paysheet.paysheetCancelAll');
    Route::put('/paysheetCancelAll', 'paysheetController@paysheetCancelAll')->name('paysheet.paysheetCancelAll');
    
    Route::post('/paysheetApproveAll', 'paysheetController@paysheetApproveAll')->name('paysheet.paysheetApproveAll');
    Route::put('/paysheetApproveAll', 'paysheetController@paysheetApproveAll')->name('paysheet.paysheetApproveAll');
    
    /*------------------------------------------------------------------*/
    /*                      System Routes
    /*------------------------------------------------------------------*/
    Route::post('/attendances/generateAttendanceReport', 'AttendanceController@generateAttendanceReport')->name('attendance.generateAttendanceReport');
    Route::get('/attendances/getAttendanceReport', 'AttendanceController@getAttendanceReport')->name('attendance.getAttendanceReport');
    Route::get('/attendances/getSampleAttendance', 'AttendanceController@getSampleAttendance')->name('getSampleAttendance');
    
    Route::post('/employees/image/{id}', 'employeeController@profile')->name('employees.profile');
    Route::get('/employees/getbranches', 'employeeController@getbranches')->name('employees.getbranches');
    Route::get('/employee-list/{id}', 'employeeController@emp_list')->name('employees.emp_list');
    Route::get('/employees/filter', 'employeeController@filter')->name('employees.filter');
    Route::get('/employees/export', 'employeeController@export')->name('employees.export');
    Route::get('/employees/profile', 'employeeController@emp_profile')->name('employees.emp_profile');
    Route::resource('/employees', 'employeeController');
    Route::post('/employees/saveEmployee', 'employeeController@store')->name('saveEmployee');
    Route::post('/employees/updateEmployee', 'employeeController@update')->name('updateEmployee');
    Route::post('selected/company', 'HomeController@setCompany')->name('setCompany');
    
    Route::post('/leaves_balance/getBalance', 'LeaveBalanceController@getBalance')->name('leaves_balance.getBalance');
    Route::resource('/leaves', 'LeaveController');
    Route::resource('/leaves_balance', 'LeaveBalanceController');
    
    Route::post('/payroll-approval', 'SalaryController@approve')->name('payroll.approve');
    
    Route::get('/payroll-approval', 'SalaryController@payrole_approval')->name('payroll.approval');
    
    Route::resource('/salary', 'SalaryController');
    
    Route::resource('/events', 'EventsController');
    
    Route::post('/paysheet/print', 'paysheetController@print_sheet')->name('paysheet.print');
    
    Route::post('/paysheet/payrole_with_file', 'paysheetController@payrole_with_file')->name('paysheet.payrole_with_file');
    
    Route::resource('/paysheet', 'paysheetController');
    
    Route::resource('/payslip', 'payslipController');
    
    Route::get('/employee-payslip', 'payslipController@employee_payslip')->name('payslip.employee_payslip');
    
    Route::resource('/payadvice', 'payadviceController');
    
    Route::resource('/bankfile', 'bankfileController');
    
    Route::resource('/epfcform', 'epfcformController');
    
    Route::resource('/wht', 'whtController');
    
    Route::get('importExport', 'AttendanceController@importExport');
    
    Route::post('/paysheet/payRole', 'AttendanceController@payRole')->name('attendance.payRole');
    
    Route::get('downloadExcel/{type}', 'AttendanceController@downloadExcel');
    
    Route::post('importExcel', 'AttendanceController@importExcel');
    
    Route::resource('/attendances', 'AttendanceController');
    
    Route::resource('/employee_loans', 'LoanController');
    
    Route::get('/department', 'SettingController@department')->name('settings.department');
    
    Route::post('/department', 'SettingController@store_department')->name('settings.store_department');
    
    Route::get('/department_edit', 'SettingController@edit_department')->name('settings.edit_department');
    
    Route::put('/department_update', 'SettingController@update_department')->name('settings.update_department');
    
    Route::delete('/department_delete/{id}', 'SettingController@delete_department')->name('settings.delete_department');
    
    Route::get('/theme', 'SettingController@theme')->name('settings.theme');
    
    Route::put('/companies/logo_update/{id}', 'CompanyController@logo_update')->name('companies.logo_update');
    
    Route::put('/companies/bank_update/{id}', 'CompanyController@bank_update')->name('companies.bank_update');
    
    Route::put('/companies/tax_details_update/{id}', 'CompanyController@tax_details_update')->name('companies.tax_details_update');
    
    Route::put('/companies/profile_conatcts_update/{id}', 'CompanyController@profile_conatcts_update')->name('companies.profile_conatcts_update');
    
    Route::put('/companies/leave_details_update/{id}', 'CompanyController@leave_details_update')->name('companies.leave_details_update');
    Route::post('/companies/assignUserToCompany', 'CompanyController@assignUserToCompany');
    
    Route::get('/clear-cache', function () {
        $exitCode = Artisan::call('config:clear');
        $exitCode = Artisan::call('cache:clear');
        $exitCode = Artisan::call('config:cache');
        $exitCode = Artisan::call('view:clear');
        $exitCode = Artisan::call('route:clear');
        return 'DONE';
    });
    
    
    Route::get('/storage', function () {
        
        symlink('/home/clientcorporates/ERP/storage/app/public', '/home/clientcorporates/public_html/storage');
        
        echo "Storage Linked";
    });
    
    
    Route::get('/mail', 'MailController@index')->name('Mail.index');
    
    Route::post('/send', 'MailController@send_mail')->name('Mail.send');
    
    Route::post('/bankfile/getBnkFile', 'bankfileController@downloadBankFileText')->name('GetBankFile');
    Route::post('/bankfile/getEpfFile', 'epfcformController@downloadEpfFileText')->name('GetEpfFile');
    Route::post('/bankfile/getEtfFile', 'epfcformController@downloadEtfFileText')->name('GetEtfFile');
    Route::post('/attendances/getAttendance', 'AttendanceController@filterAttendance')->name('GetAttendance');
    
    Route::get('/employees/getReportingManager', 'employeeController@getReportingManager')->name('employees.getReportingManager');
    Route::post('/shifts/destroyShift','CompanyController@destroyShift')->name('destroyShift');
    
    Route::get('/temp/{id}', 'SettingController@temp')->name('settings.temp');

app/company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class company extends Model
{
    public function allowance(){
        return $this->hasOne('App\Allowance','company_id','regno');
    }
    
    public function employees(){
        return $this->hasMany('App\Employee','company_id', 'regno');
    }
    
    public function employeesWithoutResign(){
        return $this->hasMany('App\Employee','company_id', 'regno')->where('date_of_resign', null);
    }
    
    public function getAttendance() {
        return $this->belongsToMany('App\Emplyee', 'attendance','user_id','user_id');
    }
    
    public function user(){
        return $this->belongsTo('App\User');
    }
    
    public function departments(){
        return $this->hasMany(Department::class);
    }
    
    public function leaveTypes(){
        return $this->hasMany('App\LeaveType', 'company_id', 'regno');
    }
    
    public function shifts(){
        return $this->hasMany('App\Shift', 'company_id', 'regno');
    }
    
    public function salaries(){
        return $this->hasMany('App\Salary', 'company_id', 'regno');
    }
    
    public function leaveBalance(){
        return $this->hasMany('App\Leave_balance', 'company_id', 'regno');
    }
    
    public function leaves(){
        return $this->hasMany('App\Leave', 'company_id', 'regno');
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('title')
    <title>Corporate Solutions | Company</title>
    <style>
        .bootstrap-timepicker-widget table td a {
            border: 1px transparent solid;
            width: 100%;
            display: inline-block;
            margin: 0;
            padding: 8px 0;
            outline: 0;
            color: #333;
            background-color: #bab9b6;
            border-radius: 4px;
        }
    </style>
@endsection

@section('page_header')
    <h5 class="m-0 text-dark">Company Settings</h5>
@endsection

@section('pagenation')
    <li class="breadcrumb-item"><a href="{{'/home'}}">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="{{route('companies.index')}}">Company</a></li>
    <li class="breadcrumb-item active">Create Company</li>
@endsection

@section('content')

    <form action="{{ route('companies.store') }}" method="post" enctype="multipart/form-data" id="company">

        {{ csrf_field() }}

        @include('company.form')

        <div class="card-footer">
            <small class="pull-right">
                <a href="{{url()->previous()}}" class="btn btn-success btn-sm"><i class="fa fa-arrow-left"
                                                                                  aria-hidden="true"></i> Back</a>
                <button type="submit" class="btn btn-primary btn-sm">Add Company</button>
            </small>
        </div>

    </form>

@endsection

@section('custom-jquery')

    <script>
        $('#account_no').blur(function (e) {
            $('#account_no').val(('000000000000' + $('#account_no').val()).slice(-12));
        });

        $('#bank_code').change(function (event) {
            var bank_code = $(this).val();
            console.log(bank_code);

            $.ajax({
                url: "{{ route('employees.getbranches') }}",
                method: "get",
                data: {bank_code: bank_code},
                datatype: "json",
                success: function (data) {

                    $('#branch_code').html(data.html);

                }
            });
        });

        $('#leaves').change(function (event) {
            var leave = $("input[type='checkbox']").val();
            if ($('#leaves').is(":checked")) {
                // it is checked
                $('#leave_details_div').show();
            } else {
                $('#leave_details_div').hide();
            }
        });
        $('#leaves').ready(function (event) {
            var leave = $("input[type='checkbox']").val();
            if ($('#leaves').is(":checked")) {
                // it is checked
                $('#leave_details_div').show();
            } else {
                $('#leave_details_div').hide();
            }
        });

        $('#shift_apl').change(function(event) {
            var leave = $("input[type='checkbox']").val();
            if ($('#shift_apl').is(":checked")) {
                // it is checked
                $('.basic-time').hide();
                $( '#shift_details_div' ).show();
            }else{
                $('.basic-time').show();
                $( '#shift_details_div' ).hide();
            }
        });
        $('#shift_apl').ready(function(event) {
            var leave = $("input[type='checkbox']").val();
            if ($('#shift_apl').is(":checked")) {
                // it is checked
                $('.basic-time').hide();
                $( '#shift_details_div' ).show();
            }else{
                $('.basic-time').show();
                $( '#shift_details_div' ).hide();
            }
        });

        $(function () {
            $("#add-shift").on('click', function () {
                $( ".shifts-allocation-contents:last" ).clone().appendTo($(".shifts-allocation:last"));
            });
        });
    </script>


@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Corporate Solutions | Company</title>
@endsection

@section('page_header')
    <h5 class="m-0 text-dark">Super Admin - Company creation</h5>
@endsection

@section('pagenation')
    <li class="breadcrumb-item"><a href="{{'/home'}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Company</li>
@endsection

@section('content')

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <div class="pull-right">
                    <div class="input-group">
                        @can('create company')
                            <a href="{{ route('companies.create') }}" class="btn btn-success btn-sm"
                               data-toggle="tooltip" data-placement="top" title="New"><i class="fa fa-plus"></i></a>
                        @endcan
                    </div>
                </div>
            </h3>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped" id="example4">
                <thead>
                <tr>
                    <th>RegNo</th>
                    <th>Business Name</th>
                    <th>Telephone</th>
                    <th>E-mail</th>
                    <th>Admin</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody>
                @foreach($companies as $company)
                    <tr>
                        <td>{{$company->regno}}</td>
                        <td>{{$company->name}}</td>
                        <td>{{$company->telephone}}</td>
                        <td>{{$company->email}}</td>
                        @if(!is_null($company->user_id))
                            <td>{{ $company->user->name }}</td>
                            <td>{{ $company->user->getRoleNames()->first() }}</td>
                        @else
                            <td> - </td>
                            <td> - </td>
                        @endif
                        <td>
                            <a class="btn btn-circle btn-warning btn-sm"
                               href="{{ route('employees.emp_list', $company->regno) }}" data-toggle="tooltip"
                               title="Employees"><i class="fas fa-user-friends"></i></a>

                            @can('view company')
                                <a class="btn btn-circle btn-info btn-sm"
                                   href="{{ route('companies.show', $company->regno) }}" data-toggle="tooltip"
                                   title="View"><i class="fa fa-file-text-o" aria-hidden="true"></i></a>
                            @endcan

                            @can('edit company')
                                <a class="btn btn-circle btn-success btn-sm"
                                   href="{{ route('companies.edit', $company->id) }}" data-toggle="tooltip"
                                   title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            @endcan

                            @can('delete company')
                                <button class="btn btn-danger btn-sm" data-companyid="{{$company->id}}"
                                        data-toggle="modal" data-target="#delete"><i class="fa fa-trash"
                                                                                     aria-hidden="true"
                                                                                     data-toggle="tooltip"
                                                                                     title="Delete"></i></button>
                            @endcan
                            <button class="btn btn-circle btn-sm" style="color: #3490dc; border: 1px solid silver;"
                                    title="View Employees" data-toggle="modal" data-company="{{$company->id}}"
                                    data-target="#{{$company->id}}"><i class="fa fa-eye" data-toggle="tooltip"
                                                                       aria-hidden="true"></i></button>

                            <button class="btn btn-circle btn-sm" style="color: #3490dc; border: 1px solid silver;"
                                    title="Assign Company Admin" data-toggle="modal" data-company="{{$company->id}}"
                                    data-target="#company-admins{{$company->id}}"><i class="fa fa-user" data-toggle="tooltip"
                                                                       aria-hidden="true"></i></button>
                            @include('company.model-employee')
                            @include('company.model-company-admin')

                        </td>
                    </tr>
                @endforeach
                </tbody>

            </table>
        </div>

        <div class="row">

            <div class="col-3" style="margin-bottom: 15px; margin-left: 25px;">
                <a class="btn btn-success btn-sm" href="{{url()->previous()}}" data-toggle="tooltip" title="Back"><i
                        class="fa fa-arrow-left" aria-hidden="true"></i> Back</a>
            </div>
        </div>
    </div>


    <!-- employee model -->
    <!--end delete model-->

    <!-- delete modal -->
    <div id="delete" class="modal fade" role=".modal-dialog-centered">
        <div class="modal-dialog-lg modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="icon-box">
                        <i class="material-icons">&#xE5CD;</i>
                    </div>
                </div>
                <h1>Are you Sure ?</h1>

                <form action="{{ route('companies.destroy', '0') }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE')}}
                    <div class="modal-body">
                        <input type="hidden" name="company_id" value="" id="company_id">
                        <p>Do you really want to delete these records? This process cannot be undone.</p>
                    </div>
                    <div class="modal-footer"></div>
                    <div class="row justify-content-md-center">
                        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>&nbsp;&nbsp;
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--end delete model-->
@endsection

@section('custom-jquery')

    <script>
        $('#delete').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var id = button.data('companyid');
            console.log(id);
            var modal = $(this)
            modal.find('#company_id').val(id);
        });
    </script>

@endsection

resources/views/company/model-company-admin.blade.php
<div class="modal fade" id="company-admins{{$company->id}}">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Company Admins</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="card-body">
                    <table class="table table-bordered table-striped" id="example5">
                        <thead>
                        <tr>
                            <th class="search">Id</th>
                            <th class="search">User Name</th>
                            <th class="search">E-mail</th>
                            <th class="search">company</th>
                            <th class="search">Role</th>
                            <th>Action</th>
                        </tr>
                        </thead>

                        <tbody id="table">
                        @foreach($users as $key=>$user)
                            <tr>
                                <td>{{ $key }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
{{--                                @if($user->company_id != 'All')--}}
{{--                                    <td>{{ App\company::where('regno',$user->company_id)->first()->name }}</td>--}}
{{--                                @else--}}
                                    <td>{{ $user->company_id }}</td>
{{--                                @endif--}}
                                <td>{{ $user->getRoleNames()->first() }}</td>
                                <td>
                                    <form action="/companies/assignUserToCompany" method="post"
                                          enctype="multipart/form-data">
                                        @csrf
                                        <input type="hidden" name="user" id="user" value="{{ $user->id }}">
                                        <input type="hidden" name="company" id="company" value="{{$company->id}}">
                                        <button class="btn btn-circle btn-info btn-sm" data-toggle="tooltip"
                                                title="Assign Company Admin"><i class="fa fa-check-circle"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

resources/views/company/model-employee.blade.php
<div class="modal fade" id="{{$company->id}}">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">{{ $company->name }}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="card-body">
                    <table class="table table-bordered table-striped" id="example5">
                        <thead>
                        <tr>
                            <th class="search">Emp ID</th>
                            <th class="search">Name</th>
                            <th class="search">E-mail</th>
                            <th class="search">NIC</th>
                            <th class="search">Contact Number</th>
                            <th class="search">Gender</th>
                            <th>Action</th>
                        </tr>
                        </thead>

                        <tbody id="table">
                        @foreach($company->employees as $employee)
                            <tr>
                                <td>{{ $employee->user_id }}</td>
                                <td>{{ $employee->sname }} {{ $employee->fname }} {{ $employee->lname }}</td>
                                <td>{{ $employee->personal_email }}</td>
                                <td>{{ $employee->nic }}</td>
                                <td>{{ $employee->per_mobileno }}</td>
                                <td>{{ $employee->gender }}</td>
                                <td>

                                    @can('view employees')
                                        <a class="btn btn-circle btn-info btn-sm" href="{{ route('employees.show', $employee->id) }}" data-toggle="tooltip" title="View"><i class="fa fa-file-text-o" aria-hidden="true"></i></a>
                                    @endcan

                                    @can('edit employees')
                                        <a class="btn btn-circle btn-success btn-sm" href="{{ route('employees.edit', $employee->id) }}" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                    @endcan

                                    @can('delete employees')
                                        <button class="btn btn-danger btn-sm" data-employeeid="{{$employee->id}}" data-toggle="modal" data-target="#delete"><i class="fa fa-trash" aria-hidden="true" data-toggle="tooltip" title="Delete"></i></button>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>