routes/web.php
<?php
    
    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */
    Route::group(['middleware' => 'prevent-back-history'], function () {
        Auth::routes();
        Route::get('/home', 'HomeController@index');
    });
    
    Route::get('/', 'HomeController@index')->name('home');
    
    Auth::routes();
    
    Route::get('/home', 'HomeController@index')->name('home');


//use Illuminate\Support\Facades\Artisan;
//use Illuminate\Support\Facades\Route;

//Route::get('/', function () {
//    return view('auth.login');
//});
//
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');
    
    Route::group(['middleware' => ['role_or_permission:super-admin']], function () {
        
        Route::post('updateRolesPermissions', 'PermissionController@updateRolesPermissions');
        Route::resource('users', 'UserController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('roles', 'RoleController');
        
        
    });
    Route::resource('/companies', 'CompanyController');
    
    
    Route::put('/paysheet/paysheetCancel/{id}', 'paysheetController@paysheetCancel')->name('paysheet.paysheetCancel');
    Route::put('/paysheet/paysheetApprove/{id}', 'paysheetController@paysheetApprove')->name('paysheet.paysheetApprove');
    
    Route::post('/paysheetCancelAll', 'paysheetController@paysheetCancelAll')->name('paysheet.paysheetCancelAll');
    Route::put('/paysheetCancelAll', 'paysheetController@paysheetCancelAll')->name('paysheet.paysheetCancelAll');
    
    Route::post('/paysheetApproveAll', 'paysheetController@paysheetApproveAll')->name('paysheet.paysheetApproveAll');
    Route::put('/paysheetApproveAll', 'paysheetController@paysheetApproveAll')->name('paysheet.paysheetApproveAll');
    
    /*------------------------------------------------------------------*/
    /*                      System Routes
    /*------------------------------------------------------------------*/
    Route::post('/attendances/generateAttendanceReport', 'AttendanceController@generateAttendanceReport')->name('attendance.generateAttendanceReport');
    Route::get('/attendances/getAttendanceReport', 'AttendanceController@getAttendanceReport')->name('attendance.getAttendanceReport');
    Route::get('/attendances/getSampleAttendance', 'AttendanceController@getSampleAttendance')->name('getSampleAttendance');
    
    Route::post('/employees/image/{id}', 'employeeController@profile')->name('employees.profile');
    Route::get('/employees/getbranches', 'employeeController@getbranches')->name('employees.getbranches');
    Route::get('/employee-list/{id}', 'employeeController@emp_list')->name('employees.emp_list');
    Route::get('/employees/filter', 'employeeController@filter')->name('employees.filter');
    Route::get('/employees/export', 'employeeController@export')->name('employees.export');
    Route::get('/employees/profile', 'employeeController@emp_profile')->name('employees.emp_profile');
    Route::resource('/employees', 'employeeController');
    Route::post('/employees/saveEmployee', 'employeeController@store')->name('saveEmployee');
    Route::post('/employees/updateEmployee', 'employeeController@update')->name('updateEmployee');
    Route::post('selected/company', 'HomeController@setCompany')->name('setCompany');
    
    Route::post('/leaves_balance/getBalance', 'LeaveBalanceController@getBalance')->name('leaves_balance.getBalance');
    Route::resource('/leaves', 'LeaveController');
    Route::resource('/leaves_balance', 'LeaveBalanceController');
    
    Route::post('/payroll-approval', 'SalaryController@approve')->name('payroll.approve');
    
    Route::get('/payroll-approval', 'SalaryController@payrole_approval')->name('payroll.approval');
    
    Route::resource('/salary', 'SalaryController');
    
    Route::resource('/events', 'EventsController');
    
    Route::post('/paysheet/print', 'paysheetController@print_sheet')->name('paysheet.print');
    
    Route::post('/paysheet/payrole_with_file', 'paysheetController@payrole_with_file')->name('paysheet.payrole_with_file');
    
    Route::resource('/paysheet', 'paysheetController');
    
    Route::resource('/payslip', 'payslipController');
    
    Route::get('/employee-payslip', 'payslipController@employee_payslip')->name('payslip.employee_payslip');
    
    Route::resource('/payadvice', 'payadviceController');
    
    Route::resource('/bankfile', 'bankfileController');
    
    Route::resource('/epfcform', 'epfcformController');
    
    Route::resource('/wht', 'whtController');
    
    Route::get('importExport', 'AttendanceController@importExport');
    
    Route::post('/paysheet/payRole', 'AttendanceController@payRole')->name('attendance.payRole');
    
    Route::get('downloadExcel/{type}', 'AttendanceController@downloadExcel');
    
    Route::post('importExcel', 'AttendanceController@importExcel');
    
    Route::resource('/attendances', 'AttendanceController');
    
    Route::resource('/employee_loans', 'LoanController');
    
    Route::get('/department', 'SettingController@department')->name('settings.department');
    
    Route::post('/department', 'SettingController@store_department')->name('settings.store_department');
    
    Route::get('/department_edit', 'SettingController@edit_department')->name('settings.edit_department');
    
    Route::put('/department_update', 'SettingController@update_department')->name('settings.update_department');
    
    Route::delete('/department_delete/{id}', 'SettingController@delete_department')->name('settings.delete_department');
    
    Route::get('/theme', 'SettingController@theme')->name('settings.theme');
    
    Route::put('/companies/logo_update/{id}', 'CompanyController@logo_update')->name('companies.logo_update');
    
    Route::put('/companies/bank_update/{id}', 'CompanyController@bank_update')->name('companies.bank_update');
    
    Route::put('/companies/tax_details_update/{id}', 'CompanyController@tax_details_update')->name('companies.tax_details_update');
    
    Route::put('/companies/profile_conatcts_update/{id}', 'CompanyController@profile_conatcts_update')->name('companies.profile_conatcts_update');
    
    Route::put('/companies/leave_details_update/{id}', 'CompanyController@leave_details_update')->name('companies.leave_details_update');
    Route::post('/companies/assignUserToCompany', 'CompanyController@assignUserToCompany');
    
    Route::get('/clear-cache', function () {
        $exitCode = Artisan::call('config:clear');
        $exitCode = Artisan::call('cache:clear');
        $exitCode = Artisan::call('config:cache');
        $exitCode = Artisan::call('view:clear');
        $exitCode = Artisan::call('route:clear');
        return 'DONE';
    });
    
    
    Route::get('/storage', function () {
        
        symlink('/home/clientcorporates/ERP/storage/app/public', '/home/clientcorporates/public_html/storage');
        
        echo "Storage Linked";
    });
    
    
    Route::get('/mail', 'MailController@index')->name('Mail.index');
    
    Route::post('/send', 'MailController@send_mail')->name('Mail.send');
    
    Route::post('/bankfile/getBnkFile', 'bankfileController@downloadBankFileText')->name('GetBankFile');
    Route::post('/bankfile/getEpfFile', 'epfcformController@downloadEpfFileText')->name('GetEpfFile');
    Route::post('/bankfile/getEtfFile', 'epfcformController@downloadEtfFileText')->name('GetEtfFile');
    Route::post('/attendances/getAttendance', 'AttendanceController@filterAttendance')->name('GetAttendance');
    
    Route::get('/employees/getReportingManager', 'employeeController@getReportingManager')->name('employees.getReportingManager');
    Route::post('/shifts/destroyShift','CompanyController@destroyShift')->name('destroyShift');
    
    Route::get('/temp/{id}', 'SettingController@temp')->name('settings.temp');

app/Leave.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{
    public function employee(){
        return $this->belongsTo('App\Employee', 'user_id', 'user_id');
    }
    
    public function company(){
        return $this->belongsTo('App\company', 'regno', 'company_id');
    }
    
    public function type(){
        return $this->hasOne('App\LeaveTypes', 'id', 'type');
    }
}

app/LeaveType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LeaveType extends Model
{
    //
}

app/Http/Controllers/LeaveController.php
<?php
    
    namespace App\Http\Controllers;
    
    use App\company;
    use App\Employee;
    use App\Leave;
    use App\Leave_balance;
    use App\User;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\DB;
    
    class LeaveController extends Controller {
        /**
         * LeaveController constructor.
         */
        public function __construct () { $this->middleware('auth'); }
        
        /**
         * Display a listing of the resource.
         * @return \Illuminate\Http\Response
         */
        public function index () {
            $leaves = null;
            $employees = null;
            $company = null;
            $role = auth()->user()->getRoleNames()->first();
//            dd(is_null(session('company')));
            if (!is_null(session('company'))) {
                $company = company::findOrFail(session('company'));
    
                if ($role == "employee") {
                    $leaves = Leave::where('company_id', session('company_id'))->where('reporting_Manager', '=', auth()->user()->employee->reporting_manager)->get();
                    $employees = auth()->user()->employee;
                } else {
                    $leaves = $company->leaves;
                }
                
            }else
                alert()->error('Please select a company');
            
            
            return view('leave.index', compact('leaves', 'employees'));
        }
        
        /**
         * Show the form for creating a new resource.
         * @return \Illuminate\Http\Response
         */
        public function create () {
            //
        }
        
        /**
         * Store a newly created resource in storage.
         * @param \Illuminate\Http\Request $request
         * @return \Illuminate\Http\Response
         */
        public function store (Request $request) {
            $this->validate($request, [
                'user_id' => 'required',
                'type' => 'required',
                'reason' => 'required',
                'date' => 'required',
            ]);
            $repManagerId = Employee::where([['company_id', session('company_id')], ['user_id', $request->user_id]])->first()->reporting_manager;
            if (!is_null($repManagerId)) {
                $leave = new Leave();
                $leave->user_id = $request->user_id;
                $leave->company_id = $request->company_id;
                $leave->date = $request->date;
                $leave->type = $request->type;
                $leave->reporting_Manager = $repManagerId;
                $leave->reason = $request->reason;
                $leave->approved_status = 'pending';
                $leave->calc_status = 'pending';
                $leave->save();
                $manager_email = Employee::where('company_id', session('company_id'))->where('user_id', $request->reporting_manager)->value('off_email');
                alert()->success('Leave created successfully');
                return redirect(route('leaves.index'))->with('success', 'Leave created successfully');
            } else {
                alert()->error('Cannot create a Leave.<br> This employee must have a Reporting Manager');
                return redirect(route('leaves.index'));
            }
        }
        
        /**
         * Display the specified resource.
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function show ($id) {
            $leaves = Leave::where([['company_id', session('company_id')],['user_id', $id]])->get();
            $leave_balance = Leave_balance::where('company_id', session('company_id'))->where('user_id', '=', $id)->get();
//            dd($leave_balance);
            $remainingLeaves = 0;
            $usedLeaves = 0;
            foreach ($leave_balance as $lBalance){
                $remainingLeaves += $lBalance->remaining;
                $usedLeaves += $lBalance->used;
            }
            return view('leave.show', compact('leaves', 'leave_balance', 'remainingLeaves', 'usedLeaves'));
        }
        
        /**
         * Show the form for editing the specified resource.
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function edit ($id) {
            //
        }
        
        /**
         * Update the specified resource in storage.
         * @param \Illuminate\Http\Request $request
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function update (Request $request, $id) {
            DB::beginTransaction();
            $leaves = Leave::findOrFail($id);
            $leaves->approved_status = 'accepted';
            $userid = $leaves->user_id;
            $leaves->update();
            
            $balance_id = Leave_balance::where([['company_id', session('company_id')], ['user_id', $userid], ['leave_type', $leaves->type]])->first()->id;
            $balance = Leave_balance::findOrFail($balance_id);
            $balance->used = $balance->used + 1;
            $balance->remaining = $balance->remaining - 1;
            $balance->update();
            DB::commit();
            alert()->success('Leave Approved successfully');
            return back();
        }
        
        /**
         * Remove the specified resource from storage.
         * @param int $id
         * @return \Illuminate\Http\Response
         */
        public function destroy (Request $request, $id) {
            $leaves = Leave::findOrFail($id);
            $leaves->approved_status = 'rejected';
            $leaves->update();
            return redirect(route('leaves.index'))->with('success', 'Leave deleted successfully');
        }
    }

resources/views/leave/index.blade.php
@extends('layouts.app')

@section('title')
    <title>Talent | leaves</title>
@endsection

@section('page_header')
    <h5 class="m-0 text-dark">leave Management</h5>
@endsection

@section('pagenation')
    <li class="breadcrumb-item"><a href="{{'/home'}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Leave Details</li>
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <small class="pull-right">
                    @can('create leave')
                        <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#new"><i
                                class="fa fa-plus" aria-hidden="true" data-toggle="tooltip" title="New"></i></button>
                    @endcan
                </small>
            </h3>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped" id="example1">
                <thead>
                <tr>
                    <th class="search">Id</th>
                    <th class="search">Employee Name</th>
                    <th class="search">Leave type</th>
                    <th class="search">Date</th>
                    <th class="search">Category</th>
                    <th class="search">Reason</th>
                    <th class="search">Approve</th>
                    <th class="search">Action</th>
                </tr>
                </thead>

                <tbody>
                @if(!is_null($leaves))
                    @foreach($leaves as $leave)
                        {{--                    {{ dd($leave) }}--}}
                        <tr>
                            <td>{{$leave->user_id}}</td>
                            @role('employee')
                            <td>{{ $employees->name_with_initials }}</td>
                            {{--                        @endrole--}}
                            {{--                        @role('super-admin|company-admin')--}}
                            @else
                                @php
                                    $employee = App\Employee::where('user_id', $leave->user_id)->first();
                                @endphp
                                <td>{{ $employee->name_with_initials }}</td>
                                @endrole
                                @php
                                    $type = App\LeaveType::findOrFail($leave->type);
                                @endphp
                                <td>{{$type->name}}</td>
                                <td>{{$leave->date}}</td>
                                <td>{{$type->type}}</td>
                                <td>{{$leave->reason}}</td>
                                @if($leave->approved_status=='pending')
                                    <td><span class="badge badge-warning">Pending</span></td>
                                @elseif($leave->approved_status=='accepted')
                                    <td><span class="badge badge-success">Approved</span></td>
                                @else
                                    <td><span class="badge badge-danger">Rejected</span></td>
                                @endif
                                <td>
                                    <form action="{{ route('leaves.update',$leave->id) }}" method="post">
                                        {{csrf_field()}}
                                        {{ method_field('PUT') }}
                                        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-check"
                                                                                                data-toggle="tooltip"
                                                                                                data-placement="top"
                                                                                                title="Approve"
                                                                                                aria-hidden="true"
                                                                                                style="color: #fff;"></i>
                                        </button>
                                    </form>
                                </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>

            </table>
        </div>

        <div class="row">
            <div class="col-3" style="margin-bottom: 15px; margin-left: 25px;">
                <a class="btn btn-success btn-sm" href="{{url()->previous()}}"><i class="fa fa-arrow-left"
                                                                                  aria-hidden="true"></i> Back</a>
            </div>
        </div>

    </div>


    <!-- create model -->
    <div class="modal fade" id="new" tabindex="-1" role=".modal-dialog-centered" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add a new Leave</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <form action="{{ route('leaves.store')}}" method="POST" id="leave">
                    {{ csrf_field() }}
                    <div class="modal-body">
                        @include('leave.form')
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary btn-sm">Add Leave</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end create model -->


    <!-- delete modal -->
    <div id="delete" class="modal fade" role=".modal-dialog-centered">
        <div class="modal-dialog modal-confirm">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="icon-box">
                        <i class="material-icons">&#xE5CD;</i>
                    </div>
                </div>
                <h1>Are you Sure ?</h1>

                <form action="{{ route('leaves.destroy', '0') }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE')}}
                    <div class="modal-body">
                        <input type="hidden" name="leave_id" value="" id="leave_id">
                        <p>Do you really want to delete these records? This process cannot be undone.</p>
                    </div>
                    <div class="modal-footer"></div>
                    <div class="row justify-content-md-center">
                        <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>&nbsp;&nbsp;
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('custom-jquery')
    <script>
        $('#delete').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget)
            var id = button.data('leaveid');
            console.log(id);
            var modal = $(this)
            modal.find('#leave_id').val(id);
        });
    </script>


@endsection

resources/views/leave/leave_balance.blade.php
@extends('layouts.app')

@section('title')
    <title>Talent | leaves</title>
@endsection

@section('page_header')
    <h5 class="m-0 text-dark">Leave Balance Management</h5>
@endsection

@section('pagenation')
    <li class="breadcrumb-item"><a href="{{'/home'}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Leave Balance</li>
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"></h3>
            <form action="{{ route('leaves_balance.getBalance')}}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-3">
                        <div class="form-group">
                            <select name="type" class="form-control" id="type" required>
                                <option value="" selected>Select the type</option>
                                @foreach($leaves_type as $type)
                                    <option value="{{$type->id}}">{{$type->name}} ({{$type->type}})</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-success btn-sm" type="submit"><i class="fa fa-search" aria-hidden="true"
                                                                                data-toggle="tooltip" title="New"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped" id="example1">
                <thead>
                <tr>
                    <th class="search">Id</th>
                    <th class="search">Employee ID</th>
                    <th class="search">Employee Name</th>
                    <th class="search">Leave Type</th>
                    <th class="search">Total</th>
                    <th class="search">Used</th>
                    <th class="search">Available</th>
                </tr>
                </thead>

                <tbody id="balanceTable">
                @foreach($leaves_balance as $key=>$Lblance)
                    <tr>
                        <th class="search">{{$key+1}}</th>
                        <th class="search">{{$Lblance->user_id}}</th>
                        <th class="search">{{App\Employee::where('user_id',$Lblance->user_id)->first()['name_with_initials']}}</th>
                        <th class="search">{{App\LeaveType::findOrFail($Lblance->leave_type)->name}}</th>
                        <th class="search">{{ (float)$Lblance->used+(float)$Lblance->remaining }}</th>
                        <th class="search">{{$Lblance->used}}</th>
                        <th class="search">{{$Lblance->remaining}}</th>
                    </tr>
                @endforeach
                </tbody>

            </table>
        </div>

        <div class="row">
            <div class="col-3" style="margin-bottom: 15px; margin-left: 25px;">
                <a class="btn btn-success btn-sm" href="{{url()->previous()}}"><i class="fa fa-arrow-left"
                                                                                  aria-hidden="true"></i> Back</a>
            </div>
        </div>
    </div>


    <!-- create model -->
{{--    <div class="modal fade" id="new" tabindex="-1" role=".modal-dialog-centered" aria-labelledby="exampleModalLabel"--}}
{{--         aria-hidden="true">--}}
{{--        <div class="modal-dialog">--}}
{{--            <div class="modal-content">--}}
{{--                <div class="modal-header">--}}
{{--                    <h5 class="modal-title">Add a new Leave Balance</h5>--}}
{{--                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
{{--                        <span aria-hidden="true">&times;</span>--}}
{{--                    </button>--}}
{{--                </div>--}}

{{--                <form action="{{ route('leaves_balance.store')}}" method="POST">--}}
{{--                    {{ csrf_field() }}--}}
{{--                    <div class="modal-body">--}}
{{--                        <div class="form-group">--}}
{{--                            <div class="form-row">--}}
{{--                                <label for="studentFirstName">Employee Name</label>--}}
{{--                                <select class="form-control" name="emp_name">--}}
{{--                                    <option selected>Select Employee</option>--}}
{{--                                    @foreach ($employees as $employee)--}}
{{--                                        <option--}}
{{--                                            value="{{$employee->id}}">{{$employee->fname}} {{$employee->lname}}</option>--}}
{{--                                    @endforeach--}}
{{--                                </select>--}}
{{--                            </div>--}}
{{--                        </div>--}}

{{--                        <div class="form-group">--}}
{{--                            <div class="form-row">--}}
{{--                                <div class="col">--}}
{{--                                    <label for="studentFirstName">Total Leaves</label>--}}
{{--                                    <input type="number" class="form-control" name="total_leaves"--}}
{{--                                           placeholder="Total Leaves">--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}

{{--                        <div class="form-group">--}}
{{--                            <div class="form-row">--}}
{{--                                <div class="col">--}}
{{--                                    <label for="studentFirstName">Used Leaves</label>--}}
{{--                                    <input type="number" class="form-control" name="approved_leaves"--}}
{{--                                           placeholder="Available Leaves">--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}

{{--                    <div class="modal-footer">--}}
{{--                        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>--}}
{{--                        <button type="submit" class="btn btn-primary btn-sm">Add Leave Balance</button>--}}
{{--                    </div>--}}
{{--                </form>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
    <!-- end create model -->


@endsection

@section('custom-jquery')
    <script>

        {{--$('#type').change(function (event) {--}}
        {{--    var type = $(this).val();--}}
        {{--    console.log(type);--}}

        {{--    $.ajax({--}}
        {{--        url: "{{ route('leaves_balance.getBalance') }}",--}}
        {{--        method: "get",--}}
        {{--        data: {type: type},--}}
        {{--        datatype: "json",--}}
        {{--        success: function (data) {--}}
        {{--            console.log(data);--}}
        {{--            $('#balanceTable').html(data.html);--}}
        {{--        }--}}
        {{--    });--}}
        {{--});--}}
    </script>
@endsection